services:
  - type: web
    name: task-management-api
    env: ruby
    plan: free
    buildCommand: ./render-build.sh
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production}
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task_management_db
          property: connectionString
      - key: SECRET_KEY_BASE
        value: {{ SECRET_KEY_BASE }}
      - key: JWT_SECRET_KEY
        value: {{ JWT_SECRET_KEY }}
      - key: REDIS_URL
        fromService:
          name: task-management-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: {{ RAILS_MASTER_KEY }}
      - key: GMAIL_USERNAME
        value: {{ GMAIL_USERNAME }}
      - key: GMAIL_PASSWORD
        value: {{ GMAIL_PASSWORD }}
      - key: MAILER_HOST
        value: task-management-api.onrender.com
    healthCheckPath: /health

databases:
  - name: task_management_db
    type: postgresql
    plan: free

redis:
  - name: task-management-redis
    plan: free
    maxmemoryPolicy: noeviction

workers:
  - type: background
    name: sidekiq
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task_management_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: task-management-redis
          property: connectionString
      - key: SECRET_KEY_BASE
        value: {{ SECRET_KEY_BASE }}
      - key: JWT_SECRET_KEY
        value: {{ JWT_SECRET_KEY }}
      - key: RAILS_MASTER_KEY
        value: {{ RAILS_MASTER_KEY }}
      - key: GMAIL_USERNAME
        value: {{ GMAIL_USERNAME }}
      - key: GMAIL_PASSWORD
        value: {{ GMAIL_PASSWORD }}
      - key: MAILER_HOST
        value: task-management-api.onrender.com

cronJobs:
  - name: task_cleanup
    schedule: "0 0 * * *"
    command: bundle exec rake task:cleanup
    envVars:
      - key: RAILS_ENV
        value: production
